---
# This carries out tasks needed to get the content generator running.

- name: ensure kgen user exists
  user:      name=kgen
             groups=www-data

- name: Make sure node etc is installed (need git for npm)
  apt: name={{item}} state=installed
  with_items:
       - npm
       - nodejs
       - nodejs-legacy
       - git

- name: ensure KoTE release downloaded
  get_url:   dest=/home/kgen/KingOfTheEtherThrone-{{kote_version}}.zip
             url=https://github.com/kieranelby/KingOfTheEtherThrone/archive/v{{kote_version}}.zip
             force=yes

- name: ensure KoTE release unpacked
  unarchive: dest=/home/kgen
             src=/home/kgen/KingOfTheEtherThrone-{{kote_version}}.zip
             owner=kgen group=kgen
             copy=no

- name: link release into current dir
  file: src=/home/kgen/KingOfTheEtherThrone-{{kote_version}} dest=/home/kgen/KingOfTheEtherThrone owner=kgen group=kgen state=link

- name: ensure shell script is executable
  file: path=/home/kgen/KingOfTheEtherThrone/bin/refresh.sh mode=u+x

- name: ensure kgen service definition exists
  copy:      dest=/etc/systemd/system/kgen.service
             src=roles/genserver/files/kgen.service
             mode=644 owner=root group=root
  register:  kgenservicedefinition

- name: ensure systemd is reloaded if geth.service has changed
  command:   systemctl daemon-reload
  when:      kgenservicedefinition.changed

- name: ensure kgen is restarted
  # TODO - perhaps we should only restart if we downloaded a new version or changed the service definition?
  service:   name=kgen state=restarted

- name: ensure kgen is enabled (that is, will start on boot)
  command:   systemctl enable kgen
  
